-- budget_topline_lines: generated by _build_budget_seed.py.
-- Source: DoD comptroller FY27 budget justification books (public).
-- Re-applying is safe (every INSERT carries ON CONFLICT DO NOTHING).

INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milpers_mpaf_basic$$, $$mpaf$$, $$AirForce$$, $$Active$$, $$MILPERS$$, NULL, NULL, $$Military Personnel, Air Force$$, 36433653000, 37525437000, 39656728000, 159127000, 39815855000, $$Military Personnel, Air Force.

Account type: MILPERS
Service: AirForce (Active)

Funding (USD billions):
  FY24 actual:    $36.434B
  FY25 enacted:   $37.525B
  FY26 disc:      $39.657B
  FY26 recon:     $0.159B
  FY26 total:     $39.816B
  FY27 disc:      $41.415B
  FY27 total:     $41.415B

Source: Budget J-Books/FY26/Remaining/FY2026_m1.pdf (page 6)$$, $$Budget J-Books/FY26/Remaining/FY2026_m1.pdf$$, 6, NULL, $${"fy27_v159": {"line": "Military Personnel, Air Force", "disc_K": 41414873, "mand_K": 0, "source": "FY2027_m1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:21:52.2306+00:00$$, 41414873000, 0, 41414873000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milpers_mpaf_medicare$$, $$mpaf$$, $$AirForce$$, $$Active$$, $$MILPERS$$, NULL, NULL, $$Medicare-Eligible Retiree Health Fund Contribution, Air Force$$, 2047980000, 2192081000, 2527335000, 0, 2527335000, $$Medicare-Eligible Retiree Health Fund Contribution, Air Force.

Account type: MILPERS
Service: AirForce (Active)

Funding (USD billions):
  FY24 actual:    $2.048B
  FY25 enacted:   $2.192B
  FY26 disc:      $2.527B
  FY26 total:     $2.527B
  FY27 disc:      $2.806B
  FY27 total:     $2.806B

Source: Budget J-Books/FY26/Remaining/FY2026_m1.pdf (page 8)$$, $$Budget J-Books/FY26/Remaining/FY2026_m1.pdf$$, 8, NULL, $${"fy27_v159": {"line": "Medicare-Eligible Retiree Health Fund Contribution, Air Force", "disc_K": 2806058, "mand_K": 0, "source": "FY2027_m1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:21:52.2306+00:00$$, 2806058000, 0, 2806058000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$recon_af_om$$, NULL, $$AirForce$$, $$NA$$, $$ReconciliationOnly$$, NULL, NULL, $$AF/SF O&M reconciliation backfill — not captured in budget_om_sags$$, NULL, NULL, 191000000, 4527000000, 4718000000, $$AF/SF O&M reconciliation backfill — not captured in budget_om_sags.

Account type: ReconciliationOnly
Service: AirForce (NA)

Funding (USD billions):
  FY26 disc:      $0.191B
  FY26 recon:     $4.527B
  FY26 total:     $4.718B

Source: Budget J-Books/FY26/Remaining/FY2026_Budget_Request_Overview_Book.pdf (page 128)$$, $$Budget J-Books/FY26/Remaining/FY2026_Budget_Request_Overview_Book.pdf$$, 128, NULL, NULL, FALSE, NULL, NULL, $$2026-05-06T19:30:18.456592+00:00$$, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$recon_af_rdte$$, NULL, $$AirForce$$, $$NA$$, $$ReconciliationOnly$$, NULL, NULL, $$AF/SF RDT&E reconciliation backfill — not captured in budget_pes initial AF R-1 ingest$$, NULL, NULL, 0, 11929923000, 11929923000, $$AF/SF RDT&E reconciliation backfill — not captured in budget_pes initial AF R-1 ingest.

Account type: ReconciliationOnly
Service: AirForce (NA)

Funding (USD billions):
  FY26 disc:      $0.000B
  FY26 recon:     $11.930B
  FY26 total:     $11.930B

Source: Budget J-Books/FY26/Remaining/FY2026_Budget_Request_Overview_Book.pdf (page 128)$$, $$Budget J-Books/FY26/Remaining/FY2026_Budget_Request_Overview_Book.pdf$$, 128, NULL, NULL, FALSE, NULL, NULL, $$2026-05-06T19:30:18.456592+00:00$$, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milpers_mpsf_medicare$$, $$mpsf$$, $$SpaceForce$$, $$Active$$, $$MILPERS$$, NULL, NULL, $$Medicare-Eligible Retiree Health Fund Contribution, Space Force$$, 58016000, 67063000, 80543000, 0, 80543000, $$Medicare-Eligible Retiree Health Fund Contribution, Space Force.

Account type: MILPERS
Service: SpaceForce (Active)

Funding (USD billions):
  FY24 actual:    $0.058B
  FY25 enacted:   $0.067B
  FY26 disc:      $0.081B
  FY26 total:     $0.081B
  FY27 disc:      $0.100B
  FY27 total:     $0.100B

Source: Budget J-Books/FY26/Remaining/FY2026_m1.pdf (page 8)$$, $$Budget J-Books/FY26/Remaining/FY2026_m1.pdf$$, 8, NULL, $${"fy27_v159": {"line": "Medicare-Eligible Retiree Health Fund Contribution, Space Force", "disc_K": 100318, "mand_K": 0, "source": "FY2027_m1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:21:52.2306+00:00$$, 100318000, 0, 100318000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milcon_mca$$, $$mca$$, $$Army$$, $$Active$$, $$MILCON$$, NULL, NULL, $$Military Construction, Army$$, NULL, NULL, 2173959000, 0, 2173959000, $$Military Construction, Army.

Account type: MILCON
Service: Army (Active)

Funding (USD billions):
  FY26 disc:      $2.174B
  FY26 total:     $2.174B
  FY27 disc:      $1.932B
  FY27 total:     $1.932B

Source: Budget J-Books/FY26/Remaining/Reserve Army Military Construction.pdf (page 3)$$, $$Budget J-Books/FY26/Remaining/Reserve Army Military Construction.pdf$$, 3, NULL, $${"fy27_v160": {"line": "Military Construction, Army", "disc_K": 1931638, "mand_K": 0, "source": "FY2027_c1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:24:44.178853+00:00$$, 1931638000, 0, 1931638000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milcon_mcng$$, $$mcng$$, $$Army$$, $$Guard$$, $$MILCON$$, NULL, NULL, $$Military Construction, Army National Guard$$, NULL, NULL, 151880000, 0, 151880000, $$Military Construction, Army National Guard.

Account type: MILCON
Service: Army (Guard)

Funding (USD billions):
  FY26 disc:      $0.152B
  FY26 total:     $0.152B
  FY27 disc:      $0.359B
  FY27 total:     $0.359B

Source: Budget J-Books/FY26/Remaining/National Guard Army Military Construction.pdf (page 3)$$, $$Budget J-Books/FY26/Remaining/National Guard Army Military Construction.pdf$$, 3, NULL, $${"fy27_v160": {"line": "Military Construction, Army National Guard", "disc_K": 358909, "mand_K": 0, "source": "FY2027_c1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:24:44.178853+00:00$$, 358909000, 0, 358909000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milpers_rpmc_basic$$, $$rpmc$$, $$MarineCorps$$, $$Reserve$$, $$MILPERS$$, NULL, NULL, $$Reserve Personnel, Marine Corps$$, 914617000, 944225000, 1019171000, 4114000, 1023285000, $$Reserve Personnel, Marine Corps.

Account type: MILPERS
Service: MarineCorps (Reserve)

Funding (USD billions):
  FY24 actual:    $0.915B
  FY25 enacted:   $0.944B
  FY26 disc:      $1.019B
  FY26 recon:     $0.004B
  FY26 total:     $1.023B
  FY27 disc:      $1.066B
  FY27 total:     $1.066B

Source: Budget J-Books/FY26/Remaining/FY2026_m1.pdf (page 6)$$, $$Budget J-Books/FY26/Remaining/FY2026_m1.pdf$$, 6, NULL, $${"fy27_v159": {"line": "Reserve Personnel, Marine Corps", "disc_K": 1065922, "mand_K": 0, "source": "FY2027_m1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:21:52.2306+00:00$$, 1065922000, 0, 1065922000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milpers_rpmc_medicare$$, $$rpmc$$, $$MarineCorps$$, $$Reserve$$, $$MILPERS$$, NULL, NULL, $$Medicare-Eligible Retiree Health Fund Contribution, Reserve Pers., MC$$, 94316000, 92828000, 107730000, 0, 107730000, $$Medicare-Eligible Retiree Health Fund Contribution, Reserve Pers., MC.

Account type: MILPERS
Service: MarineCorps (Reserve)

Funding (USD billions):
  FY24 actual:    $0.094B
  FY25 enacted:   $0.093B
  FY26 disc:      $0.108B
  FY26 total:     $0.108B
  FY27 disc:      $0.123B
  FY27 total:     $0.123B

Source: Budget J-Books/FY26/Remaining/FY2026_m1.pdf (page 7)$$, $$Budget J-Books/FY26/Remaining/FY2026_m1.pdf$$, 7, NULL, $${"fy27_v159": {"line": "Medicare-Eligible Retiree Health Fund Contribution, Reserve Pers., MC", "disc_K": 122767, "mand_K": 0, "source": "FY2027_m1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:21:52.2306+00:00$$, 122767000, 0, 122767000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$revmgmt_residual$$, $$rmgmt$$, $$DefenseWide$$, $$NA$$, $$RevolvingMgmt$$, NULL, NULL, $$Revolving and Management Funds (residual not in budget_pes)$$, NULL, NULL, 1522000000, 0, 4185000000, $$Revolving and Management Funds (residual not in budget_pes).

Account type: RevolvingMgmt
Service: DefenseWide (NA)

Funding (USD billions):
  FY26 disc:      $1.522B
  FY26 total:     $4.185B
  FY27 disc:      $7.508B
  FY27 mand:      $18.748B
  FY27 total:     $26.256B

Source: Budget J-Books/FY26/Remaining/FY2026_Budget_Request_Overview_Book.pdf (page 127)$$, $$Budget J-Books/FY26/Remaining/FY2026_Budget_Request_Overview_Book.pdf$$, 127, NULL, $${"fy27_v181": {"table": "Table A-1", "source": "fy27_pb_overview_book_a1_v181", "rationale": "Methodology shift: full A-1 Rev/Mgmt total replaces incorrect residual-after-DPA-DSCCP-subtraction", "source_pdf": "Budget J-Books/FY27/Remaining/FY2027_Budget_Request_Overview_Book.pdf", "fy27_disc_M": 7508, "fy27_mand_M": 18748, "fy26_total_M": 4185, "fy27_total_M": 26256}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:29:01.323968+00:00$$, 7508000000, 18748000000, 26256000000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milcon_mcar$$, $$mcar$$, $$Army$$, $$Reserve$$, $$MILCON$$, NULL, NULL, $$Military Construction, Army Reserve$$, NULL, NULL, 42239000, 0, 42239000, $$Military Construction, Army Reserve.

Account type: MILCON
Service: Army (Reserve)

Funding (USD billions):
  FY26 disc:      $0.042B
  FY26 total:     $0.042B
  FY27 disc:      $0.210B
  FY27 total:     $0.210B

Source: Budget J-Books/FY26/Remaining/Reserve Army Military Construction.pdf (page 3)$$, $$Budget J-Books/FY26/Remaining/Reserve Army Military Construction.pdf$$, 3, NULL, $${"fy27_v160": {"line": "Military Construction, Army Reserve", "disc_K": 209913, "mand_K": 0, "source": "FY2027_c1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:24:44.178853+00:00$$, 209913000, 0, 209913000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milpers_ngpa_basic$$, $$ngpa$$, $$Army$$, $$Guard$$, $$MILPERS$$, NULL, NULL, $$National Guard Personnel, Army$$, 10015582000, 10019623000, 10509845000, 15167000, 10525012000, $$National Guard Personnel, Army.

Account type: MILPERS
Service: Army (Guard)

Funding (USD billions):
  FY24 actual:    $10.016B
  FY25 enacted:   $10.020B
  FY26 disc:      $10.510B
  FY26 recon:     $0.015B
  FY26 total:     $10.525B
  FY27 disc:      $11.555B
  FY27 total:     $11.555B

Source: Budget J-Books/FY26/Remaining/FY2026_m1.pdf (page 6)$$, $$Budget J-Books/FY26/Remaining/FY2026_m1.pdf$$, 6, NULL, $${"fy27_v159": {"line": "National Guard Personnel, Army", "disc_K": 11555125, "mand_K": 0, "source": "FY2027_m1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:21:52.2306+00:00$$, 11555125000, 0, 11555125000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milpers_mpsf_basic$$, $$mpsf$$, $$SpaceForce$$, $$Active$$, $$MILPERS$$, NULL, NULL, $$Military Personnel, Space Force$$, 1265565000, 1312647000, 1496908000, 8229000, 1505137000, $$Military Personnel, Space Force.

Account type: MILPERS
Service: SpaceForce (Active)

Funding (USD billions):
  FY24 actual:    $1.266B
  FY25 enacted:   $1.313B
  FY26 disc:      $1.497B
  FY26 recon:     $0.008B
  FY26 total:     $1.505B
  FY27 disc:      $1.825B
  FY27 total:     $1.825B

Source: Budget J-Books/FY26/Remaining/FY2026_m1.pdf (page 6)$$, $$Budget J-Books/FY26/Remaining/FY2026_m1.pdf$$, 6, NULL, $${"fy27_v159": {"line": "Military Personnel, Space Force", "disc_K": 1825228, "mand_K": 0, "source": "FY2027_m1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:21:52.2306+00:00$$, 1825228000, 0, 1825228000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$fh_fha$$, $$fha$$, $$Army$$, $$NA$$, $$FamilyHousing$$, NULL, NULL, $$Family Housing, Army$$, NULL, NULL, 606976000, 0, 606976000, $$Family Housing, Army.

Account type: FamilyHousing
Service: Army (NA)

Funding (USD billions):
  FY26 disc:      $0.607B
  FY26 total:     $0.607B
  FY27 disc:      $0.709B
  FY27 mand:      $0.862B
  FY27 total:     $1.571B

Source: Budget J-Books/FY26/Remaining/Regular Army Military Construction, Army Family Housing and Homeowners Assistance.pdf (page 3)$$, $$Budget J-Books/FY26/Remaining/Regular Army Military Construction, Army Family Housing and Homeowners Assistance.pdf$$, 3, NULL, $${"fy27_v160": {"line": "Family Housing, Army (Construction)", "note": "C-1 Summary Table TOA = FH Construction Army; FH O&M Army $479,815K reported separately and not part of this appropriation total", "disc_K": 708902, "mand_K": 861602, "source": "FY2027_c1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:24:44.178853+00:00$$, 708902000, 861602000, 1570504000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$fh_fhn$$, $$fhn$$, $$Navy$$, $$NA$$, $$FamilyHousing$$, NULL, NULL, $$Family Housing, Navy and Marine Corps$$, NULL, NULL, 551705000, 0, 551705000, $$Family Housing, Navy and Marine Corps.

Account type: FamilyHousing
Service: Navy (NA)

Funding (USD billions):
  FY26 disc:      $0.552B
  FY26 total:     $0.552B
  FY27 disc:      $0.747B
  FY27 mand:      $0.725B
  FY27 total:     $1.473B

Source: Budget J-Books/FY26/Remaining/MCON_Book.pdf (page 3)$$, $$Budget J-Books/FY26/Remaining/MCON_Book.pdf$$, 3, NULL, $${"fy27_v160": {"line": "Family Housing, Navy (Construction)", "disc_K": 747479, "mand_K": 725264, "source": "FY2027_c1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:24:44.178853+00:00$$, 747479000, 725264000, 1472743000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$fh_fhaf$$, $$fhaf$$, $$AirForce$$, $$NA$$, $$FamilyHousing$$, NULL, NULL, $$Family Housing, Air Force$$, NULL, NULL, 633995000, 0, 633995000, $$Family Housing, Air Force.

Account type: FamilyHousing
Service: AirForce (NA)

Funding (USD billions):
  FY26 disc:      $0.634B
  FY26 total:     $0.634B
  FY27 disc:      $0.610B
  FY27 mand:      $0.691B
  FY27 total:     $1.301B

Source: Budget J-Books/FY26/Remaining/FY26 Air Force MILCON.pdf (page 4)$$, $$Budget J-Books/FY26/Remaining/FY26 Air Force MILCON.pdf$$, 4, NULL, $${"fy27_v160": {"line": "Family Housing, Air Force (Construction)", "disc_K": 609778, "mand_K": 690767, "source": "FY2027_c1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:24:44.178853+00:00$$, 609778000, 690767000, 1300545000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$fh_fhdw$$, $$fhdw$$, $$DefenseWide$$, $$NA$$, $$FamilyHousing$$, NULL, NULL, $$Family Housing, Defense-Wide$$, NULL, NULL, 53374000, 0, 53374000, $$Family Housing, Defense-Wide.

Account type: FamilyHousing
Service: DefenseWide (NA)

Funding (USD billions):
  FY26 disc:      $0.053B
  FY26 total:     $0.053B
  FY27 disc:      $0.063B
  FY27 total:     $0.063B

Source: Budget J-Books/FY26/Remaining/Military_Construction_Defense-Wide_Consolidated.pdf (page 3)$$, $$Budget J-Books/FY26/Remaining/Military_Construction_Defense-Wide_Consolidated.pdf$$, 3, NULL, $${"fy27_v160": {"line": "Family Housing, Defense-Wide", "disc_K": 63064, "mand_K": 0, "source": "FY2027_c1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:24:44.178853+00:00$$, 63064000, 0, 63064000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$fh_fhif$$, $$fhif$$, $$DefenseWide$$, $$NA$$, $$FamilyHousing$$, NULL, NULL, $$Family Housing Improvement Fund$$, NULL, NULL, 8315000, 0, 8315000, $$Family Housing Improvement Fund.

Account type: FamilyHousing
Service: DefenseWide (NA)

Funding (USD billions):
  FY26 disc:      $0.008B
  FY26 total:     $0.008B
  FY27 disc:      $0.008B
  FY27 total:     $0.008B

Source: Budget J-Books/FY26/Remaining/Reserve Army Military Construction.pdf (page 3)$$, $$Budget J-Books/FY26/Remaining/Reserve Army Military Construction.pdf$$, 3, NULL, $${"fy27_v160": {"line": "Family Housing Improvement Fund", "disc_K": 8412, "mand_K": 0, "source": "FY2027_c1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:24:44.178853+00:00$$, 8412000, 0, 8412000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$fh_muhif$$, $$muhif$$, $$DefenseWide$$, $$NA$$, $$FamilyHousing$$, NULL, NULL, $$Military Unaccompanied Housing Improvement Fund$$, NULL, NULL, 497000, 0, 497000, $$Military Unaccompanied Housing Improvement Fund.

Account type: FamilyHousing
Service: DefenseWide (NA)

Funding (USD billions):
  FY26 disc:      $0.000B
  FY26 total:     $0.000B
  FY27 disc:      $0.001B
  FY27 total:     $0.001B

Source: Budget J-Books/FY26/Remaining/Reserve Army Military Construction.pdf (page 3)$$, $$Budget J-Books/FY26/Remaining/Reserve Army Military Construction.pdf$$, 3, NULL, $${"fy27_v160": {"line": "Military Unaccompanied Housing Improvement Fund", "disc_K": 501, "mand_K": 0, "source": "FY2027_c1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:24:44.178853+00:00$$, 501000, 0, 501000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$drug_total$$, $$drug$$, $$DefenseWide$$, $$NA$$, $$DrugInterdiction$$, NULL, NULL, $$Drug Interdiction and Counter-Drug Activities, Defense$$, 1177061000, 1110436000, 904301000, 0, 904301000, $$Drug Interdiction and Counter-Drug Activities, Defense.

Account type: DrugInterdiction
Service: DefenseWide (NA)

Funding (USD billions):
  FY24 actual:    $1.177B
  FY25 enacted:   $1.110B
  FY26 disc:      $0.904B
  FY26 total:     $0.904B
  FY27 disc:      $0.918B
  FY27 total:     $0.918B

Source: Budget J-Books/FY26/Remaining/FY2026_Drug_Interdiction_and_Counter-Drug_Activities.pdf (page 4)$$, $$Budget J-Books/FY26/Remaining/FY2026_Drug_Interdiction_and_Counter-Drug_Activities.pdf$$, 4, NULL, $${"fy27_v161": {"note": "O-1 line is authoritative; no separate Drug Interdiction J-Book in FY27 PB repo", "applied_at": "2026-05-08 18:14:35.279122+00", "source_pdf": "O&M/FY27/FY2027_o1.txt", "fy27_disc_K": 918002, "fy27_mand_K": 0, "source_line": "Drug Interdiction and Counter-Drug Activities, Defense", "source_section": "Transfer Accounts"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:27:12.710225+00:00$$, 918002000, 0, 918002000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milpers_mpmc_medicare$$, $$mpmc$$, $$MarineCorps$$, $$Active$$, $$MILPERS$$, NULL, NULL, $$Medicare-Eligible Retiree Health Fund Contribution, Marine Corps$$, 1102941000, 1175602000, 1348044000, 0, 1348044000, $$Medicare-Eligible Retiree Health Fund Contribution, Marine Corps.

Account type: MILPERS
Service: MarineCorps (Active)

Funding (USD billions):
  FY24 actual:    $1.103B
  FY25 enacted:   $1.176B
  FY26 disc:      $1.348B
  FY26 total:     $1.348B
  FY27 disc:      $1.492B
  FY27 total:     $1.492B

Source: Budget J-Books/FY26/Remaining/FY2026_m1.pdf (page 7)$$, $$Budget J-Books/FY26/Remaining/FY2026_m1.pdf$$, 7, NULL, $${"fy27_v159": {"line": "Medicare-Eligible Retiree Health Fund Contribution, Marine Corps", "disc_K": 1492085, "mand_K": 0, "source": "FY2027_m1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:21:52.2306+00:00$$, 1492085000, 0, 1492085000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$ctef_total$$, $$ctef$$, $$Army$$, $$NA$$, $$CTEF$$, NULL, NULL, $$Counter-ISIS Train and Equip Fund$$, 397950000, 528699557, 357516000, 0, 357516000, $$Counter-ISIS Train and Equip Fund.

Account type: CTEF
Service: Army (NA)

Funding (USD billions):
  FY24 actual:    $0.398B
  FY25 enacted:   $0.529B
  FY26 disc:      $0.358B
  FY26 total:     $0.358B

Source: Budget J-Books/FY26/Remaining/Counter-Islamic State of Iraq and Syria Train and Equip Fund.pdf (page 5)$$, $$Budget J-Books/FY26/Remaining/Counter-Islamic State of Iraq and Syria Train and Equip Fund.pdf$$, 5, NULL, $${"fy27_v161": {"note": "O-1 line gives $303,099K FY27 disc; sum of 4 SAGs in budget_om_sags matches to-the-K.", "applied_at": "2026-05-08 18:15:03.395574+00", "source_pdf": "O&M/FY27/FY2027_o1.txt", "fy27_disc_K": 303099, "fy27_mand_K": 0, "fy27_status": "covered_in_om_sags", "source_line": "Counter-Islamic State of Iraq and Syria Train and Equip", "fy27_replacement_table": "budget_om_sags", "fy27_replacement_appropriation_id": "ctef"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:27:12.710225+00:00$$, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$recon_army_om$$, NULL, $$Army$$, $$NA$$, $$ReconciliationOnly$$, NULL, NULL, $$Army O&M reconciliation/disc backfill — not captured in budget_om_sags$$, NULL, NULL, 3819000000, 2316000000, 6135000000, $$Army O&M reconciliation/disc backfill — not captured in budget_om_sags.

Account type: ReconciliationOnly
Service: Army (NA)

Funding (USD billions):
  FY26 disc:      $3.819B
  FY26 recon:     $2.316B
  FY26 total:     $6.135B

Source: Budget J-Books/FY26/Remaining/FY2026_Budget_Request_Overview_Book.pdf (page 128)$$, $$Budget J-Books/FY26/Remaining/FY2026_Budget_Request_Overview_Book.pdf$$, 128, NULL, NULL, FALSE, NULL, NULL, $$2026-05-06T19:30:18.456592+00:00$$, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$recon_defwide_offset$$, NULL, $$DefenseWide$$, $$NA$$, $$ReconciliationOnly$$, NULL, NULL, $$Defense-Wide classification offset — DB exceeds A-3 DefWide total by ~$5.49B (likely DHP/recon double-attribution)$$, NULL, NULL, -5490000000, 0, -5490000000, $$Defense-Wide classification offset — DB exceeds A-3 DefWide total by ~$5.49B (likely DHP/recon double-attribution).

Account type: ReconciliationOnly
Service: DefenseWide (NA)

Funding (USD billions):
  FY26 disc:      $-5.490B
  FY26 total:     $-5.490B

Source: Budget J-Books/FY26/Remaining/FY2026_Budget_Request_Overview_Book.pdf (page 128)$$, $$Budget J-Books/FY26/Remaining/FY2026_Budget_Request_Overview_Book.pdf$$, 128, NULL, NULL, FALSE, NULL, NULL, $$2026-05-06T19:30:18.456592+00:00$$, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milpers_mpa_basic$$, $$mpa$$, $$Army$$, $$Active$$, $$MILPERS$$, NULL, NULL, $$Military Personnel, Army$$, 51409194000, 51819421000, 55206157000, 180027000, 55386184000, $$Military Personnel, Army.

Account type: MILPERS
Service: Army (Active)

Funding (USD billions):
  FY24 actual:    $51.409B
  FY25 enacted:   $51.819B
  FY26 disc:      $55.206B
  FY26 recon:     $0.180B
  FY26 total:     $55.386B
  FY27 disc:      $56.939B
  FY27 total:     $56.939B

Source: Budget J-Books/FY26/Remaining/FY2026_m1.pdf (page 6)$$, $$Budget J-Books/FY26/Remaining/FY2026_m1.pdf$$, 6, NULL, $${"fy27_v159": {"line": "Military Personnel, Army", "disc_K": 56938524, "mand_K": 0, "source": "FY2027_m1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:21:52.2306+00:00$$, 56938524000, 0, 56938524000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milpers_mpa_medicare$$, $$mpa$$, $$Army$$, $$Active$$, $$MILPERS$$, NULL, NULL, $$Medicare-Eligible Retiree Health Fund Contribution, Army$$, 2846715000, 3022322000, 3551323000, 0, 3551323000, $$Medicare-Eligible Retiree Health Fund Contribution, Army.

Account type: MILPERS
Service: Army (Active)

Funding (USD billions):
  FY24 actual:    $2.847B
  FY25 enacted:   $3.022B
  FY26 disc:      $3.551B
  FY26 total:     $3.551B
  FY27 disc:      $3.972B
  FY27 total:     $3.972B

Source: Budget J-Books/FY26/Remaining/FY2026_m1.pdf (page 7)$$, $$Budget J-Books/FY26/Remaining/FY2026_m1.pdf$$, 7, NULL, $${"fy27_v159": {"line": "Medicare-Eligible Retiree Health Fund Contribution, Army", "disc_K": 3972161, "mand_K": 0, "source": "FY2027_m1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:21:52.2306+00:00$$, 3972161000, 0, 3972161000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milpers_rpa_basic$$, $$rpa$$, $$Army$$, $$Reserve$$, $$MILPERS$$, NULL, NULL, $$Reserve Personnel, Army$$, 5373771000, 5490830000, 5833586000, 6938000, 5840524000, $$Reserve Personnel, Army.

Account type: MILPERS
Service: Army (Reserve)

Funding (USD billions):
  FY24 actual:    $5.374B
  FY25 enacted:   $5.491B
  FY26 disc:      $5.834B
  FY26 recon:     $0.007B
  FY26 total:     $5.841B
  FY27 disc:      $6.003B
  FY27 total:     $6.003B

Source: Budget J-Books/FY26/Remaining/FY2026_m1.pdf (page 6)$$, $$Budget J-Books/FY26/Remaining/FY2026_m1.pdf$$, 6, NULL, $${"fy27_v159": {"line": "Reserve Personnel, Army", "disc_K": 6003189, "mand_K": 0, "source": "FY2027_m1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:21:52.2306+00:00$$, 6003189000, 0, 6003189000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milpers_rpa_medicare$$, $$rpa$$, $$Army$$, $$Reserve$$, $$MILPERS$$, NULL, NULL, $$Medicare-Eligible Retiree Health Fund Contribution, Reserve Pers., Army$$, 510346000, 511378000, 589595000, 0, 589595000, $$Medicare-Eligible Retiree Health Fund Contribution, Reserve Pers., Army.

Account type: MILPERS
Service: Army (Reserve)

Funding (USD billions):
  FY24 actual:    $0.510B
  FY25 enacted:   $0.511B
  FY26 disc:      $0.590B
  FY26 total:     $0.590B
  FY27 disc:      $0.640B
  FY27 total:     $0.640B

Source: Budget J-Books/FY26/Remaining/FY2026_m1.pdf (page 7)$$, $$Budget J-Books/FY26/Remaining/FY2026_m1.pdf$$, 7, NULL, $${"fy27_v159": {"line": "Medicare-Eligible Retiree Health Fund Contribution, Reserve Pers., Army", "disc_K": 639807, "mand_K": 0, "source": "FY2027_m1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:21:52.2306+00:00$$, 639807000, 0, 639807000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milpers_ngpa_medicare$$, $$ngpa$$, $$Army$$, $$Guard$$, $$MILPERS$$, NULL, NULL, $$Medicare-Eligible Retiree Health Fund Contribution, Guard Pers., Army$$, 943772000, 953525000, 1089594000, 0, 1089594000, $$Medicare-Eligible Retiree Health Fund Contribution, Guard Pers., Army.

Account type: MILPERS
Service: Army (Guard)

Funding (USD billions):
  FY24 actual:    $0.944B
  FY25 enacted:   $0.954B
  FY26 disc:      $1.090B
  FY26 total:     $1.090B
  FY27 disc:      $1.239B
  FY27 total:     $1.239B

Source: Budget J-Books/FY26/Remaining/FY2026_m1.pdf (page 7)$$, $$Budget J-Books/FY26/Remaining/FY2026_m1.pdf$$, 7, NULL, $${"fy27_v159": {"line": "Medicare-Eligible Retiree Health Fund Contribution, Guard Pers., Army", "disc_K": 1239331, "mand_K": 0, "source": "FY2027_m1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:21:52.2306+00:00$$, 1239331000, 0, 1239331000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milpers_mpn_basic$$, $$mpn$$, $$Navy$$, $$Active$$, $$MILPERS$$, NULL, NULL, $$Military Personnel, Navy$$, 37503139000, 39284587000, 41221902000, 169759000, 41391661000, $$Military Personnel, Navy.

Account type: MILPERS
Service: Navy (Active)

Funding (USD billions):
  FY24 actual:    $37.503B
  FY25 enacted:   $39.285B
  FY26 disc:      $41.222B
  FY26 recon:     $0.170B
  FY26 total:     $41.392B
  FY27 disc:      $43.929B
  FY27 total:     $43.929B

Source: Budget J-Books/FY26/Remaining/FY2026_m1.pdf (page 6)$$, $$Budget J-Books/FY26/Remaining/FY2026_m1.pdf$$, 6, NULL, $${"fy27_v159": {"line": "Military Personnel, Navy", "disc_K": 43929362, "mand_K": 0, "source": "FY2027_m1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:21:52.2306+00:00$$, 43929362000, 0, 43929362000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milpers_mpn_medicare$$, $$mpn$$, $$Navy$$, $$Active$$, $$MILPERS$$, NULL, NULL, $$Medicare-Eligible Retiree Health Fund Contribution, Navy$$, 2175657000, 2263510000, 2680874000, 0, 2680874000, $$Medicare-Eligible Retiree Health Fund Contribution, Navy.

Account type: MILPERS
Service: Navy (Active)

Funding (USD billions):
  FY24 actual:    $2.176B
  FY25 enacted:   $2.264B
  FY26 disc:      $2.681B
  FY26 total:     $2.681B
  FY27 disc:      $3.023B
  FY27 total:     $3.023B

Source: Budget J-Books/FY26/Remaining/FY2026_m1.pdf (page 7)$$, $$Budget J-Books/FY26/Remaining/FY2026_m1.pdf$$, 7, NULL, $${"fy27_v159": {"line": "Medicare-Eligible Retiree Health Fund Contribution, Navy", "disc_K": 3022776, "mand_K": 0, "source": "FY2027_m1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:21:52.2306+00:00$$, 3022776000, 0, 3022776000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milpers_mpmc_basic$$, $$mpmc$$, $$MarineCorps$$, $$Active$$, $$MILPERS$$, NULL, NULL, $$Military Personnel, Marine Corps$$, 15419439000, 16176283000, 17146360000, 118430000, 17264790000, $$Military Personnel, Marine Corps.

Account type: MILPERS
Service: MarineCorps (Active)

Funding (USD billions):
  FY24 actual:    $15.419B
  FY25 enacted:   $16.176B
  FY26 disc:      $17.146B
  FY26 recon:     $0.118B
  FY26 total:     $17.265B
  FY27 disc:      $17.868B
  FY27 total:     $17.868B

Source: Budget J-Books/FY26/Remaining/FY2026_m1.pdf (page 6)$$, $$Budget J-Books/FY26/Remaining/FY2026_m1.pdf$$, 6, NULL, $${"fy27_v159": {"line": "Military Personnel, Marine Corps", "disc_K": 17868345, "mand_K": 0, "source": "FY2027_m1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:21:52.2306+00:00$$, 17868345000, 0, 17868345000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milpers_rpn_basic$$, $$rpn$$, $$Navy$$, $$Reserve$$, $$MILPERS$$, NULL, NULL, $$Reserve Personnel, Navy$$, 2474233000, 2566620000, 2736595000, 5225000, 2741820000, $$Reserve Personnel, Navy.

Account type: MILPERS
Service: Navy (Reserve)

Funding (USD billions):
  FY24 actual:    $2.474B
  FY25 enacted:   $2.567B
  FY26 disc:      $2.737B
  FY26 recon:     $0.005B
  FY26 total:     $2.742B
  FY27 disc:      $2.798B
  FY27 total:     $2.798B

Source: Budget J-Books/FY26/Remaining/FY2026_m1.pdf (page 6)$$, $$Budget J-Books/FY26/Remaining/FY2026_m1.pdf$$, 6, NULL, $${"fy27_v159": {"line": "Reserve Personnel, Navy", "disc_K": 2797683, "mand_K": 0, "source": "FY2027_m1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:21:52.2306+00:00$$, 2797683000, 0, 2797683000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milpers_rpn_medicare$$, $$rpn$$, $$Navy$$, $$Reserve$$, $$MILPERS$$, NULL, NULL, $$Medicare-Eligible Retiree Health Fund Contribution, Reserve Pers., Navy$$, 183698000, 187400000, 218348000, 0, 218348000, $$Medicare-Eligible Retiree Health Fund Contribution, Reserve Pers., Navy.

Account type: MILPERS
Service: Navy (Reserve)

Funding (USD billions):
  FY24 actual:    $0.184B
  FY25 enacted:   $0.187B
  FY26 disc:      $0.218B
  FY26 total:     $0.218B
  FY27 disc:      $0.242B
  FY27 total:     $0.242B

Source: Budget J-Books/FY26/Remaining/FY2026_m1.pdf (page 7)$$, $$Budget J-Books/FY26/Remaining/FY2026_m1.pdf$$, 7, NULL, $${"fy27_v159": {"line": "Medicare-Eligible Retiree Health Fund Contribution, Reserve Pers., Navy", "disc_K": 241853, "mand_K": 0, "source": "FY2027_m1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:21:52.2306+00:00$$, 241853000, 0, 241853000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milpers_rpaf_basic$$, $$rpaf$$, $$AirForce$$, $$Reserve$$, $$MILPERS$$, NULL, NULL, $$Reserve Personnel, Air Force$$, 2416691000, 2597273000, 2740547000, 5223000, 2745770000, $$Reserve Personnel, Air Force.

Account type: MILPERS
Service: AirForce (Reserve)

Funding (USD billions):
  FY24 actual:    $2.417B
  FY25 enacted:   $2.597B
  FY26 disc:      $2.741B
  FY26 recon:     $0.005B
  FY26 total:     $2.746B
  FY27 disc:      $2.844B
  FY27 total:     $2.844B

Source: Budget J-Books/FY26/Remaining/FY2026_m1.pdf (page 6)$$, $$Budget J-Books/FY26/Remaining/FY2026_m1.pdf$$, 6, NULL, $${"fy27_v159": {"line": "Reserve Personnel, Air Force", "disc_K": 2844302, "mand_K": 0, "source": "FY2027_m1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:21:52.2306+00:00$$, 2844302000, 0, 2844302000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milpers_rpaf_medicare$$, $$rpaf$$, $$AirForce$$, $$Reserve$$, $$MILPERS$$, NULL, NULL, $$Medicare-Eligible Retiree Health Fund Contribution, Reserve Pers., AF$$, 198046000, 196363000, 225417000, 0, 225417000, $$Medicare-Eligible Retiree Health Fund Contribution, Reserve Pers., AF.

Account type: MILPERS
Service: AirForce (Reserve)

Funding (USD billions):
  FY24 actual:    $0.198B
  FY25 enacted:   $0.196B
  FY26 disc:      $0.225B
  FY26 total:     $0.225B
  FY27 disc:      $0.247B
  FY27 total:     $0.247B

Source: Budget J-Books/FY26/Remaining/FY2026_m1.pdf (page 8)$$, $$Budget J-Books/FY26/Remaining/FY2026_m1.pdf$$, 8, NULL, $${"fy27_v159": {"line": "Medicare-Eligible Retiree Health Fund Contribution, Reserve Pers., AF", "disc_K": 247016, "mand_K": 0, "source": "FY2027_m1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:21:52.2306+00:00$$, 247016000, 0, 247016000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milpers_ngpaf_basic$$, $$ngpaf$$, $$AirForce$$, $$Guard$$, $$MILPERS$$, NULL, NULL, $$National Guard Personnel, Air Force$$, 5339034000, 5287499000, 5598786000, 14718000, 5613504000, $$National Guard Personnel, Air Force.

Account type: MILPERS
Service: AirForce (Guard)

Funding (USD billions):
  FY24 actual:    $5.339B
  FY25 enacted:   $5.287B
  FY26 disc:      $5.599B
  FY26 recon:     $0.015B
  FY26 total:     $5.614B
  FY27 disc:      $5.918B
  FY27 total:     $5.918B

Source: Budget J-Books/FY26/Remaining/FY2026_m1.pdf (page 6)$$, $$Budget J-Books/FY26/Remaining/FY2026_m1.pdf$$, 6, NULL, $${"fy27_v159": {"line": "National Guard Personnel, Air Force", "disc_K": 5918475, "mand_K": 0, "source": "FY2027_m1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:21:52.2306+00:00$$, 5918475000, 0, 5918475000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milpers_ngpaf_medicare$$, $$ngpaf$$, $$AirForce$$, $$Guard$$, $$MILPERS$$, NULL, NULL, $$Medicare-Eligible Retiree Health Fund Contribution, Guard Pers., AF$$, 371867000, 384233000, 431362000, 0, 431362000, $$Medicare-Eligible Retiree Health Fund Contribution, Guard Pers., AF.

Account type: MILPERS
Service: AirForce (Guard)

Funding (USD billions):
  FY24 actual:    $0.372B
  FY25 enacted:   $0.384B
  FY26 disc:      $0.431B
  FY26 total:     $0.431B
  FY27 disc:      $0.465B
  FY27 total:     $0.465B

Source: Budget J-Books/FY26/Remaining/FY2026_m1.pdf (page 8)$$, $$Budget J-Books/FY26/Remaining/FY2026_m1.pdf$$, 8, NULL, $${"fy27_v159": {"line": "Medicare-Eligible Retiree Health Fund Contribution, Guard Pers., AF", "disc_K": 465097, "mand_K": 0, "source": "FY2027_m1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:21:52.2306+00:00$$, 465097000, 0, 465097000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milpers_reimbursables_offset$$, NULL, NULL, NULL, $$MILPERS$$, NULL, NULL, $$Less Reimbursables (offset to MILPERS gross)$$, -2058451000, -1636434000, -1363448000, 0, -1363448000, $$Less Reimbursables (offset to MILPERS gross).

Account type: MILPERS

Funding (USD billions):
  FY24 actual:    $-2.058B
  FY25 enacted:   $-1.636B
  FY26 disc:      $-1.363B
  FY26 total:     $-1.363B
  FY27 disc:      $-1.389B
  FY27 total:     $-1.389B

Source: Budget J-Books/FY26/Remaining/FY2026_m1.pdf (page 8)$$, $$Budget J-Books/FY26/Remaining/FY2026_m1.pdf$$, 8, NULL, $${"fy27_v159": {"line": "Less Reimbursables (offset to MILPERS gross)", "disc_K": -1389097, "mand_K": 0, "source": "FY2027_m1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:21:52.2306+00:00$$, -1389097000, 0, -1389097000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milcon_mcn$$, $$mcn$$, $$Navy$$, $$Active$$, $$MILCON$$, NULL, NULL, $$Military Construction, Navy and Marine Corps$$, NULL, NULL, 6012677000, 749184000, 6761861000, $$Military Construction, Navy and Marine Corps.

Account type: MILCON
Service: Navy (Active)

Funding (USD billions):
  FY26 disc:      $6.013B
  FY26 recon:     $0.749B
  FY26 total:     $6.762B
  FY27 disc:      $8.267B
  FY27 total:     $8.267B

Source: Budget J-Books/FY26/Remaining/Reserve Army Military Construction.pdf (page 3)$$, $$Budget J-Books/FY26/Remaining/Reserve Army Military Construction.pdf$$, 3, NULL, $${"fy27_v160": {"line": "Military Construction, Navy and Marine Corps", "disc_K": 8266703, "mand_K": 0, "source": "FY2027_c1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:24:44.178853+00:00$$, 8266703000, 0, 8266703000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milcon_mcnr$$, $$mcnr$$, $$Navy$$, $$Reserve$$, $$MILCON$$, NULL, NULL, $$Military Construction, Navy Reserve$$, NULL, NULL, 2255000, 0, 2255000, $$Military Construction, Navy Reserve.

Account type: MILCON
Service: Navy (Reserve)

Funding (USD billions):
  FY26 disc:      $0.002B
  FY26 total:     $0.002B
  FY27 disc:      $0.132B
  FY27 total:     $0.132B

Source: Budget J-Books/FY26/Remaining/MCNR_Book.pdf (page 3)$$, $$Budget J-Books/FY26/Remaining/MCNR_Book.pdf$$, 3, NULL, $${"fy27_v160": {"line": "Military Construction, Navy Reserve", "disc_K": 132272, "mand_K": 0, "source": "FY2027_c1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:24:44.178853+00:00$$, 132272000, 0, 132272000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milcon_mcaf$$, $$mcaf$$, $$AirForce$$, $$Active$$, $$MILCON$$, NULL, NULL, $$Military Construction, Air Force$$, NULL, NULL, 3721473000, 102100000, 3823573000, $$Military Construction, Air Force.

Account type: MILCON
Service: AirForce (Active)

Funding (USD billions):
  FY26 disc:      $3.721B
  FY26 recon:     $0.102B
  FY26 total:     $3.824B
  FY27 disc:      $10.601B
  FY27 total:     $10.601B

Source: Budget J-Books/FY26/Remaining/FY26 Air Force MILCON.pdf (page 3)$$, $$Budget J-Books/FY26/Remaining/FY26 Air Force MILCON.pdf$$, 3, NULL, $${"fy27_v160": {"line": "Military Construction, Air Force", "disc_K": 10601180, "mand_K": 0, "source": "FY2027_c1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:24:44.178853+00:00$$, 10601180000, 0, 10601180000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milcon_mcang$$, $$mcang$$, $$AirForce$$, $$Guard$$, $$MILCON$$, NULL, NULL, $$Military Construction, Air National Guard$$, NULL, NULL, 188646000, 5925000, 194571000, $$Military Construction, Air National Guard.

Account type: MILCON
Service: AirForce (Guard)

Funding (USD billions):
  FY26 disc:      $0.189B
  FY26 recon:     $0.006B
  FY26 total:     $0.195B
  FY27 disc:      $0.525B
  FY27 total:     $0.525B

Source: Budget J-Books/FY26/Remaining/FY26 Air National Guard MILCON.pdf (page 3)$$, $$Budget J-Books/FY26/Remaining/FY26 Air National Guard MILCON.pdf$$, 3, NULL, $${"fy27_v160": {"line": "Military Construction, Air National Guard", "disc_K": 525221, "mand_K": 0, "source": "FY2027_c1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:24:44.178853+00:00$$, 525221000, 0, 525221000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milcon_mcafr$$, $$mcafr$$, $$AirForce$$, $$Reserve$$, $$MILCON$$, NULL, NULL, $$Military Construction, Air Force Reserve$$, NULL, NULL, 60458000, 0, 60458000, $$Military Construction, Air Force Reserve.

Account type: MILCON
Service: AirForce (Reserve)

Funding (USD billions):
  FY26 disc:      $0.060B
  FY26 total:     $0.060B
  FY27 disc:      $0.022B
  FY27 total:     $0.022B

Source: Budget J-Books/FY26/Remaining/FY26 Air Force Reserve MILCON.pdf (page 3)$$, $$Budget J-Books/FY26/Remaining/FY26 Air Force Reserve MILCON.pdf$$, 3, NULL, $${"fy27_v160": {"line": "Military Construction, Air Force Reserve", "disc_K": 22172, "mand_K": 0, "source": "FY2027_c1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:24:44.178853+00:00$$, 22172000, 0, 22172000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milcon_mcdw$$, $$mcdw$$, $$DefenseWide$$, $$NA$$, $$MILCON$$, NULL, NULL, $$Military Construction, Defense-Wide$$, NULL, NULL, 3792301000, 35000000, 3827301000, $$Military Construction, Defense-Wide.

Account type: MILCON
Service: DefenseWide (NA)

Funding (USD billions):
  FY26 disc:      $3.792B
  FY26 recon:     $0.035B
  FY26 total:     $3.827B
  FY27 disc:      $3.403B
  FY27 mand:      $0.407B
  FY27 total:     $3.810B

Source: Budget J-Books/FY26/Remaining/Military_Construction_Defense-Wide_Consolidated.pdf (page 3)$$, $$Budget J-Books/FY26/Remaining/Military_Construction_Defense-Wide_Consolidated.pdf$$, 3, NULL, $${"fy27_v160": {"line": "Military Construction, Defense-Wide", "note": "Includes $217M Over-The-Horizon Radar + $190M Minor MILCON Homeland Defense per Table 2", "disc_K": 3402951, "mand_K": 407000, "source": "FY2027_c1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:24:44.178853+00:00$$, 3402951000, 407000000, 3809951000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milcon_nato$$, $$nato$$, $$DefenseWide$$, $$NA$$, $$MILCON$$, NULL, NULL, $$NATO Security Investment Program$$, NULL, NULL, 481832000, 0, 481832000, $$NATO Security Investment Program.

Account type: MILCON
Service: DefenseWide (NA)

Funding (USD billions):
  FY26 disc:      $0.482B
  FY26 total:     $0.482B
  FY27 disc:      $0.604B
  FY27 total:     $0.604B

Source: Budget J-Books/FY26/Remaining/Reserve Army Military Construction.pdf (page 3)$$, $$Budget J-Books/FY26/Remaining/Reserve Army Military Construction.pdf$$, 3, NULL, $${"fy27_v160": {"line": "NATO Security Investment Program", "disc_K": 604270, "mand_K": 0, "source": "FY2027_c1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:24:44.178853+00:00$$, 604270000, 0, 604270000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milcon_brac$$, $$brac$$, $$DefenseWide$$, $$NA$$, $$BRAC$$, NULL, NULL, $$Base Realignment & Closure Account$$, NULL, NULL, 410161000, 0, 410161000, $$Base Realignment & Closure Account.

Account type: BRAC
Service: DefenseWide (NA)

Funding (USD billions):
  FY26 disc:      $0.410B
  FY26 total:     $0.410B
  FY27 disc:      $0.372B
  FY27 total:     $0.372B

Source: Budget J-Books/FY26/Remaining/Base Realignment and Closure Account.pdf (page 3)$$, $$Budget J-Books/FY26/Remaining/Base Realignment and Closure Account.pdf$$, 3, NULL, $${"fy27_v160": {"line": "Base Realignment & Closure Account", "note": "Authoritative C-1 BA; BRAC Overview Sec III shows continuing env+caretaker $361,695K subset", "disc_K": 372317, "mand_K": 0, "source": "FY2027_c1.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:24:44.178853+00:00$$, 372317000, 0, 372317000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$milcon_cea$$, $$cea$$, $$Army$$, $$NA$$, $$Cemeterial$$, NULL, NULL, $$Cemeterial Expenses, Army$$, 188480000, 188480000, 118780000, 0, 118780000, $$Cemeterial Expenses, Army.

Account type: Cemeterial
Service: Army (NA)

Funding (USD billions):
  FY24 actual:    $0.188B
  FY25 enacted:   $0.188B
  FY26 disc:      $0.119B
  FY26 total:     $0.119B
  FY27 disc:      $0.119B
  FY27 total:     $0.119B

Source: Budget J-Books/FY26/Remaining/U.S. Army Cemeterial Expenses and Construction.pdf (page 3)$$, $$Budget J-Books/FY26/Remaining/U.S. Army Cemeterial Expenses and Construction.pdf$$, 3, NULL, $${"fy27_v160": {"line": "Cemeterial Expenses, Army FY2027 Total", "disc_K": 118780, "mand_K": 0, "source": "U.S. Army Cemeterial Expenses and Construction.txt"}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:24:44.178853+00:00$$, 118780000, 0, 118780000) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$dhp_om$$, $$dhp$$, $$DefenseWide$$, $$NA$$, $$DHP$$, $$BA-01$$, $$Operation & Maintenance$$, $$Defense Health Program — Operation & Maintenance$$, 36398946000, 38277297000, 39174590000, 2000000000, 41174590000, $$Defense Health Program — Operation & Maintenance.

Account type: DHP
Service: DefenseWide (NA)
Budget Activity: BA-01 - Operation & Maintenance

Funding (USD billions):
  FY24 actual:    $36.399B
  FY25 enacted:   $38.277B
  FY26 disc:      $39.175B
  FY26 recon:     $2.000B
  FY26 total:     $41.175B

Source: Budget J-Books/FY26/Remaining/00-DHP_Vols_I_and_II_PB26.pdf (page 4-19)$$, $$Budget J-Books/FY26/Remaining/00-DHP_Vols_I_and_II_PB26.pdf$$, 4, 19, $${"fy27_v161": {"note": "Per FY27 PB MHS J-Book: COMP $20,341,643K disc + $3,138,924K mand; PSCP $22,175,472K disc + $0 mand. Combined matches O-1 lines 180+191 to-the-K.", "applied_at": "2026-05-08 18:14:51.451409+00", "source_pdf": "Budget J-Books/FY27/MHS/MHS_PB27_J-Book-Vol1-COMP_PSCP.txt", "fy27_status": "deprecated_disaggregated", "fy27_disc_combined_K": 41131025, "fy27_mand_combined_K": 3138924, "fy27_replacement_table": "budget_om_sags", "fy27_replacement_appropriation_ids": ["om_comp", "om_pscp"]}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:23:10.531008+00:00$$, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$dhp_proc$$, $$dhp$$, $$DefenseWide$$, $$NA$$, $$DHP$$, $$BA-03$$, $$Procurement$$, $$Defense Health Program — Procurement$$, 381881000, 398867000, 354821000, 0, 354821000, $$Defense Health Program — Procurement.

Account type: DHP
Service: DefenseWide (NA)
Budget Activity: BA-03 - Procurement

Funding (USD billions):
  FY24 actual:    $0.382B
  FY25 enacted:   $0.399B
  FY26 disc:      $0.355B
  FY26 total:     $0.355B

Source: Budget J-Books/FY26/Remaining/00-DHP_Vols_I_and_II_PB26.pdf (page 4-19)$$, $$Budget J-Books/FY26/Remaining/00-DHP_Vols_I_and_II_PB26.pdf$$, 4, 19, $${"fy27_v161": {"note": "Per FY27 PB MHS J-Book: COMP $20,341,643K disc + $3,138,924K mand; PSCP $22,175,472K disc + $0 mand. Combined matches O-1 lines 180+191 to-the-K.", "applied_at": "2026-05-08 18:14:51.451409+00", "source_pdf": "Budget J-Books/FY27/MHS/MHS_PB27_J-Book-Vol1-COMP_PSCP.txt", "fy27_status": "deprecated_disaggregated", "fy27_disc_combined_K": 41131025, "fy27_mand_combined_K": 3138924, "fy27_replacement_table": "budget_om_sags", "fy27_replacement_appropriation_ids": ["om_comp", "om_pscp"]}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:23:10.531008+00:00$$, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.budget_topline_lines (id, appropriation_id, service, component, account_type, ba, ba_name, title, fy24_actual, fy25_enacted, fy26_disc, fy26_recon, fy26_total, narrative, source_pdf, source_page_start, source_page_end, raw_source, is_priority, owner, notes, created_at, fy27_disc, fy27_mand, fy27_total) VALUES ($$dhp_rdte$$, $$dhp$$, $$DefenseWide$$, $$NA$$, $$DHP$$, $$BA-02$$, $$RDT&E$$, $$Defense Health Program — RDT&E$$, 2902871000, 1695436000, 972712000, 0, 972712000, $$Defense Health Program — RDT&E.

Account type: DHP
Service: DefenseWide (NA)
Budget Activity: BA-02 - RDT&E

Funding (USD billions):
  FY24 actual:    $2.903B
  FY25 enacted:   $1.695B
  FY26 disc:      $0.973B
  FY26 total:     $0.973B

Source: Budget J-Books/FY26/Remaining/00-DHP_Vols_I_and_II_PB26.pdf (page 4-19)$$, $$Budget J-Books/FY26/Remaining/00-DHP_Vols_I_and_II_PB26.pdf$$, 4, 19, $${"fy27_v161": {"note": "Per FY27 PB MHS J-Book: COMP $20,341,643K disc + $3,138,924K mand; PSCP $22,175,472K disc + $0 mand. Combined matches O-1 lines 180+191 to-the-K.", "applied_at": "2026-05-08 18:14:51.451409+00", "source_pdf": "Budget J-Books/FY27/MHS/MHS_PB27_J-Book-Vol1-COMP_PSCP.txt", "fy27_status": "deprecated_disaggregated", "fy27_disc_combined_K": 41131025, "fy27_mand_combined_K": 3138924, "fy27_replacement_table": "budget_om_sags", "fy27_replacement_appropriation_ids": ["om_comp", "om_pscp"]}}$$::jsonb, FALSE, NULL, NULL, $$2026-05-06T19:23:10.531008+00:00$$, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
