// js/nav/drillthrough.js
//
// Drill-through helpers + left-rail sync. Three previously-adjacent
// (but non-contiguous) clusters in the inline monolith, all serving
// the same purpose: "user clicks something here -> we navigate them to
// the right tab with the right filter applied, and we keep the left
// rail's active-state and counts in sync."
//
// Cluster contents (~135 lines extracted from index.html in v196):
//
//   * Mission Control drill helpers (v100):
//       window._v98GoToSol(titleQuery)   -> Pipeline tab, filter by title
//       window._v98GoToStage(stage)      -> Pipeline tab, filter by stage
//       window._v98GoToOrg(nameQuery)    -> Orgs tab, filter by name
//       window._v98GoToHill(query)       -> Hill Ops tab, filter by summary
//     These are referenced as inline `onclick="_v98GoTo*(...)"`
//     attributes generated by js/render/mission-control.js, so they
//     must remain on the global window object.
//
//   * v100SyncRail IIFE -- a MutationObserver on #tabbar that keeps the
//     left-rail "active" class and the v98Crumb breadcrumb labels in
//     sync with whichever .tab-btn currently has .active. Polls for
//     #tabbar via setTimeout so it survives module-deferred load.
//
//   * refreshTabCounts() -- updates both the v98 rail counts
//     (.v98-rail-count[data-count]) and legacy tab counts
//     (.tab-count[data-count]) from DB.state. v126 / v128 special-case
//     for "washops" (sums hill_meetings + hill_requests instead of the
//     empty washops table).
//
//   * wireChipJumps(scope) -- delegates click handling for chip elements
//     in a given container (typically a <tbody>) with:
//       data-office-jump      -> activate Orgs, filter to that office
//       data-contact-jump     -> activate Contacts, filter to contact
//       data-legislator-jump  -> activate WashOps -> Members, filter
//
// Originally at file-scope of the inline monolith; lifted to ES module
// in v196. Same classic-script-split pattern as v181-v195.
//
// Pre-extraction audit (v185 pattern). 6 names need window exposure:
//   _v98GoToSol, _v98GoToStage, _v98GoToOrg, _v98GoToHill
//                     -- already on window via direct assignment; the
//                        original `window.X = function () {...}` lines
//                        are preserved verbatim, so no extra footer
//                        line is needed for these.
//   refreshTabCounts  -- called from monolith refreshAll() (~24594).
//                        Once refreshTabCounts lives in this module,
//                        refreshAll's call becomes external; expose.
//   wireChipJumps     -- called from contacts.js, lets.js, sols.js
//                        (3 extracted modules). Expose unconditionally.
//
// Module-internal only (NOT exposed):
//   The v100SyncRail IIFE is anonymous and self-invoking; nothing
//   outside the IIFE needs it.
//
// External file-scope refs the block consumes:
//   DB                  -- already on window (major global, no shim)
//   (audit clean -- no other file-scope const / let consumed)
//
// External function calls (all auto-hoisted to window by their
// top-level `function` decls in the classic-script monolith body):
//   activateTab        (drill helpers + IIFE + wireChipJumps)
//   legislatorById     (wireChipJumps legislator-jump handler)
//   renderOffices      (wireChipJumps office-jump handler)
//   renderContacts     (wireChipJumps contact-jump handler)

window._v98GoToSol = function (titleQuery) {
  if (typeof activateTab === 'function') activateTab('solicitations');
  setTimeout(function () {
    const s = document.getElementById('solSearch');
    if (s) { s.value = titleQuery || ''; s.dispatchEvent(new Event('input')); }
  }, 30);
};
window._v98GoToStage = function (stage) {
  if (typeof activateTab === 'function') activateTab('solicitations');
  setTimeout(function () {
    const f = document.getElementById('solStatusFilter');
    if (f) { f.value = stage || ''; f.dispatchEvent(new Event('change')); }
  }, 30);
};
window._v98GoToOrg = function (nameQuery) {
  if (typeof activateTab === 'function') activateTab('offices');
  setTimeout(function () {
    const s = document.getElementById('officesSearch');
    if (s) { s.value = nameQuery || ''; s.dispatchEvent(new Event('input')); }
  }, 30);
};
window._v98GoToHill = function (query) {
  if (typeof activateTab === 'function') activateTab('washops');
  setTimeout(function () {
    const s = document.getElementById('woSearch');
    if (s) { s.value = query || ''; s.dispatchEvent(new Event('input')); }
  }, 30);
};

// Hill Ops tab AND, when the target is a Hill member, opens the
// matching side drawer so the user lands with context. Falls back to
// the legacy summary-search behavior for non-member targets (e.g.
// committees, ad-hoc engagements).
//
// Called from the MC Hill list onclick handler (mission-control.js).
// hillBioguide is threaded via activateTab opts so the an earlier refactor
// 'washops' case in tabs.js can fire openHillMemberDrawer right after
// the renderers populate.
window._v230GoToHillEntry = function (targetType, targetId, summary) {
  if (targetType === 'member' && targetId) {
    if (typeof activateTab === 'function') {
      activateTab('washops', { hillBioguide: targetId });
    }
    return;
  }
  // Non-member target (committee, ad-hoc, etc.): fall back to legacy
  // search-by-summary behavior.
  if (typeof window._v98GoToHill === 'function') {
    window._v98GoToHill(summary || '');
  }
};

// activateTab is invoked. Watches .tab-btn class changes.
(function v100SyncRail() {
  const TAB_LABELS = {
    dashboard: ['OPS', 'Mission Control'],
    solicitations: ['OPS', 'Pipeline'],
    letters: ['OPS', 'Support'],
    washops: ['OPS', 'Hill Ops'],
    offices: ['INTEL', 'Orgs'],
    contacts: ['INTEL', 'Contacts'],
    budget: ['INTEL', 'Budget'],
    scout: ['INTEL', 'Scout'],
  };
  function sync() {
    const active = document.querySelector('.tab-btn.active');
    if (!active) return;
    const tab = active.dataset.tab;
    document.querySelectorAll('.v98-rail-link[data-v98-tab]').forEach(function (el) {
      el.classList.toggle('active', el.dataset.v98Tab === tab);
    });
    const labels = TAB_LABELS[tab];
    if (labels) {
      const grp = document.querySelector('#v98Crumb > span');
      const leaf = document.getElementById('v98CrumbLeaf');
      if (grp) grp.textContent = labels[0];
      if (leaf) leaf.textContent = labels[1];
    }
  }
  function attach() {
    const bar = document.getElementById('tabbar');
    if (!bar) { setTimeout(attach, 100); return; }
    new MutationObserver(sync).observe(bar, {
      attributes: true, attributeFilter: ['class'], subtree: true
    });
    sync();
  }
  if (document.readyState !== 'loading') attach();
  else document.addEventListener('DOMContentLoaded', attach);
})();

// ---------------------------------------------------------------

// Tab counts (rendered alongside tab labels)
function refreshTabCounts() {
  document.querySelectorAll('.v98-rail-count[data-count]').forEach(el => {
    const t = el.dataset.count;
    if (!(window.DB && DB.state)) return;
    if (t === 'washops') {
      const meets = (DB.state.hill_meetings || []).length;
      const reqs  = (DB.state.hill_requests || []).length;
      el.textContent = (meets + reqs);
    } else if (Array.isArray(DB.state[t])) {
      el.textContent = DB.state[t].length;
    }
  });
  document.querySelectorAll('.tab-count[data-count]').forEach(el => {
    // of engagement activity across all members + committees instead of the
    // useless 0 from washops. Other tabs keep their original behavior.
    if (el.dataset.count === 'washops') {
      const meets = (DB.state.hill_meetings || []).length;
      const reqs  = (DB.state.hill_requests || []).length;
      el.textContent = (meets + reqs);
    } else {
      el.textContent = (DB.state[el.dataset.count] || []).length;
    }
  });
  document.querySelectorAll('.v98-rail-count[data-count]').forEach(el => {
    if (el.dataset.count === 'washops') {
      const meets = (DB.state.hill_meetings || []).length;
      const reqs  = (DB.state.hill_requests || []).length;
      el.textContent = (meets + reqs);
    }
  });
}


// ---------------------------------------------------------------

function wireChipJumps(scope) {
  scope.querySelectorAll('[data-office-jump]').forEach(a => a.addEventListener('click', (e) => {
    e.stopPropagation();
    activateTab('offices');
    document.getElementById('officesSearch').value = (DB.get('offices', a.dataset.officeJump)||{}).name || '';
    renderOffices();
  }));
  scope.querySelectorAll('[data-contact-jump]').forEach(a => a.addEventListener('click', (e) => {
    e.stopPropagation();
    activateTab('contacts');
    const c = DB.get('contacts', a.dataset.contactJump);
    document.getElementById('contactsSearch').value = c ? ((c.firstName||'') + ' ' + (c.lastName||'')).trim() : '';
    renderContacts();
  }));
  scope.querySelectorAll('[data-legislator-jump]').forEach(a => a.addEventListener('click', (e) => {
    e.stopPropagation();
    const bg = a.dataset.legislatorJump;
    const m  = legislatorById(bg);
    if (typeof activateTab === 'function') activateTab('washops');
    const sub = document.querySelector('.subtab-btn[data-subtab="washops-members"]');
    if (sub) sub.click();
    const search = document.getElementById('hillMSearch');
    if (search && m) {
      search.value = m.full_name || m.last_name || '';
      try { search.dispatchEvent(new Event('input', { bubbles: true })); } catch (_) {}
    }
  }));
}

// =================================================================
//
// The four _v98GoTo* helpers are already on window via the
// `window._v98GoToSol = function () {...}` direct assignments above,
// so they don't need an extra exposure line here.
//
// refreshTabCounts and wireChipJumps were `function NAME()` decls in
// the classic-script monolith, so they auto-hoisted to window there.
// As module decls they do NOT auto-hoist -- expose explicitly.
// =================================================================
window.refreshTabCounts = refreshTabCounts;
window.wireChipJumps = wireChipJumps;
